# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'Self-Hosted-Agent-Lab4'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Compile project'

    #- script: |
    #    npm test -- --coverage
    #  displayName: 'Test project and generate code coverage report'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'DevOps-Group12'

- stage: Deliver
  displayName: 'Deliver Artifact'
  dependsOn: Build
  jobs:
  - job: Deliver_Artifact
    displayName: 'Deliver Artifact'
    steps:
    - download: current
      artifact: DevOps-Group12
      displayName: 'Download Artifact'
    - script: |
        echo "Deliver artifact using build tool"
      displayName: 'Deliver Artifact'

- stage: DeployToDev
  displayName: 'Deploy to Dev Env'
  dependsOn: Deliver
  jobs:
  - job: DeployToDevJob
    displayName: 'Deploy to Dev Env'
    steps:
    - script: |
        echo "Deploying artifact to Dev Env"
      displayName: 'Deploy Artifact to Dev Env'

- stage: DeployToQAT
  displayName: 'Deploy to QAT Env'
  dependsOn: DeployToDev
  jobs:
  - job: DeployToQATJob
    displayName: 'Deploy to QAT Env'
    steps:
    - script: |
        echo "Deploying artifact to QAT Env"
      displayName: 'Deploy Artifact to QAT Env'

- stage: DeployToStaging
  displayName: 'Deploy to Staging Env'
  dependsOn: DeployToQAT
  jobs:
  - job: DeployToStagingJob
    displayName: 'Deploy to Staging Env'
    steps:
    - script: |
        echo "Deploying artifact to Staging Env"
      displayName: 'Deploy Artifact to Staging Env'

- stage: DeployToProduction
  displayName: 'Deploy to Production Env'
  dependsOn: DeployToStaging
  jobs:
  - job: DeployToProductionJob
    displayName: 'Deploy to Production Env'
    steps:
    - script: |
        echo "Deploying artifact to Production Env"
      displayName: 'Deploy Artifact to Production Env'
