# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'Self-Hosted-Agent-Lab4'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Compile project'

    #- script: |
    #    npm test -- --coverage
    #  displayName: 'Test project and generate code coverage report'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'DevOps-Group12'


- stage: Deliver
  displayName: 'Deliver Artifact'
  dependsOn: Build
  jobs:
  - job: Deliver_Artifact
    displayName: 'Deliver Artifact'
    steps:
    - download: current
      artifact: DevOps-Group12
      displayName: 'Download Artifact'
    - script: |
        echo "Deliver artifact using build tool"
      displayName: 'Deliver Artifact'
