# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'Self-Hosted-Agent-Lab4'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Compile project'

    - script: |
        npm test -- --coverage
      displayName: 'Test project and generate code coverage report'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'npm install eslint'
      displayName: 'Install ESLint'

    - task: ESLint@0
      inputs:
        cwd: '.'
        customPath: 'node_modules/.bin/eslint'
      displayName: 'Run ESLint'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'ESLint Reports'
        publishLocation: 'Container'
      condition: succeededOrFailed()
